language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - valgrind

script:
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ];
    then WITH_VALGRIND=no ./build.sh;
    else ./build.sh;
    fi
